### ISSUE TITLE
v. 0.2.1 breaks the transformWrite() method work

### ISSUE THREAD

**Issue by seabrus** [jalik/jalik-ufs-gridfs#10]
Hi,

I've just updated the package to the version 0.2.1 in my app and found that the app cannot transfer data after `transformWrite()` method execution any more. 

When I save a file that should be transformed I get a message from `transformWrite()` that transformation is ended successfully but it looks like that corresponding `pipe(to)` operation is not performed: no message from the `onFinishUpload` method is sent, the file property `uploading` is always `true` and doesn't change to `false`. 

If I go back to the version 0.1.4, everything works normally. Also, if there is no transformation (i.e. the single operation `from.pipe(to);` is perform in the `transformWrite()` method) it works OK too.

Meteor: 1.4.3.2
UFS: 0.7.4_1

Looking forward for your answer.

**Comment by jalik** [comment]
Hi @seabrus, I am sorry to say that I've found nothing, I've tested the https://github.com/jalik/ufs-example using latest UFS/GRIDFS and everything works fine.. maybe it's an evironment problem ?

Have a look at this file that uses GridFSStore and `transformWrite` method :
https://github.com/jalik/ufs-example/blob/master/imports/api/files/stores/thumbnails.js

**Comment by seabrus** [comment]
Hi @jalik,

Sorry for my delay with response. 

I've compared [thumbnails.js](https://github.com/jalik/ufs-example/blob/master/imports/api/files/stores/thumbnails.js) with my file and tried the new version (0.2.1) once more. It works fine if I add `.stream()` to the call of the transformation lib:
```javascript
   transformLib(from)
      ...
      .stream().pipe(to);
```
The previous version (0.1.4) works for me when it was just
```javascript
   transformLib(from)
      ...
      .pipe(to);
```
 -- without adding `.stream()`.

So, the problem is resolved, thank you. 
Have a nice day!

**Comment by jalik** [comment]
@seabrus I am glad your problem is solved :)
