### ISSUE TITLE
`Finish` event emits twice

### ISSUE THREAD

**Issue by jdme** [jalik/jalik-ufs-gridfs#15]
Hello!

Since v3.6.6 of [npm mongodb library](https://github.com/mongodb/node-mongodb-native) _gridfs-stream_ emits `close` event along with `finish` event. The behaviour is changed by this [commit](https://github.com/mongodb/node-mongodb-native/commit/c976a01bf385941bee07fa7f021adf1d425109a8). But in your _jalik:ufs-gridfs_ library `finish` event emitting manually after `close` [here](https://github.com/jalik/meteor-jalik-ufs-gridfs/blob/56dfbfa8774c8cf26e437f071ebdbcd25cef4ce3/ufs-gridfs.js#L113), as a result we have `finish` event emitted 2 times.

So at this moment to work properly npm-mongo package of meteor should be at version v3.8.1 or less, since it depends on older version of mongodb.

**Comment by jalik** [comment]
@jdme thanks for your precise report and sorry for the very late response.
The issue has been fixed in the latest release 1.0.4.
