### ISSUE TITLE
GridFSStore is not a function

### ISSUE THREAD

**Issue by jaqua** [jalik/jalik-ufs-gridfs#9]
I have to use `new UploadFS.store.GridFS({ })`

If I use `new GridFSStore({ })` (like shown in this readme) I get the error `TypeError: GridFSStore is not a function`

**Comment by jalik** [comment]
@jaqua all my apologies, I forgot to publish the package after pushing to github... it's now working (I've checked it twice).

FYI, you can create a store by importing it like in the example, but there is a legacy way to do it like below :
```js
const Photos = new UploadFS.store.GridFS(options);
```
